name: ros2-build-and-test

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    container: ryuichiueda/ubuntu22.04-ros2:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test script
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          bash test/test.bash