name: ros2-build-and-test

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    container: ryuichiueda/ubuntu22.04-ros2:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch device_msgs
        run: |
          git clone https://github.com/TakeSomen99/device_msgs.git ../device_msgs

      - name: Run test script
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          export ROS_DOMAIN_ID=99
          export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
          ros2 daemon start

          bash test/test.bash || (
            echo "===== launch log ====="
            cat /tmp/mypkg.log
            exit 1
          )